### ISSUE TITLE
release in kinetic

### ISSUE THREAD

**Issue by sharvashish** [asmodehn/pyros-utils-release#1]
When would pyros-utils and other pyros packages be available in ros-kinetic?

**Comment by asmodehn** [comment]
I am actually working on this currently. So it will be sometime in the next
few days...

**Comment by sharvashish** [comment]
wow awesome :)

**Comment by asmodehn** [comment]
FYI : might be a bit delayed... I m currently stuck because of this bug : https://github.com/asmodehn/catkin_pip/issues/50.
Once this is solved, pyros and dependencies can be released for kinetic...

Just in case you feel like investigating ;-)
I ll be working on it when I can, but it s not my main focus for work...

**Comment by asmodehn** [comment]
Ah problem solved. Everything should be released soon !
